/*
 * generated by Xtext
 */
package csep.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import csep.ui.internal.CoffeeScriptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CoffeeScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CoffeeScriptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CoffeeScriptActivator.getInstance().getInjector(CoffeeScriptActivator.CSEP_COFFEESCRIPT);
	}
	
}
