/*
* generated by Xtext
*/
package csep.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import csep.services.CoffeeScriptGrammarAccess;

public class CoffeeScriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CoffeeScriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected csep.parser.antlr.internal.InternalCoffeeScriptParser createParser(XtextTokenStream stream) {
		return new csep.parser.antlr.internal.InternalCoffeeScriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public CoffeeScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CoffeeScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
