<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="coffeeScript" nsURI="http://www.coffeescript.org/eclipse" nsPrefix="coffeeScript">
  <eClassifiers xsi:type="ecore:EClass" name="Root"/>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//Root #//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Line" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stmt" eSuperTypes="#//Line">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequireStmt" eSuperTypes="#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedNamespace" eType="#//Id"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnStmt" eSuperTypes="#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThrowStmt" eSuperTypes="#//Stmt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//Stmt #//AssignedClassDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//SuperClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Variable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignedClassDeclaration" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//Line">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//ForValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ForSource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="by" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PrimaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//FeatureCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//FeatureCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ArgList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAccess" eSuperTypes="#//FeatureCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThisProperty" eSuperTypes="#//PrimaryExpression #//Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedPropertyAccess" eSuperTypes="#//PropertyAccess">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Id" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexedPropertyAccess" eSuperTypes="#//PropertyAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Root"/>
  <eClassifiers xsi:type="ecore:EClass" name="Case">
    <eStructuralFeatures xsi:type="ecore:EReference" name="whens" upperBound="-1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfExp" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//CondBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultBlock" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CondBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdRef" eSuperTypes="#//SuperClass #//PrimaryExpression #//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="#//Id"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prop" eType="#//Id" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Id" eSuperTypes="#//ForValue #//ThisProperty #//Variable #//DictKey #//Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="props" upperBound="-1"
        eType="#//Id" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//SuperClass #//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Expression #//Assignable"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignableArray" eSuperTypes="#//Assignable"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssignableArgList" eSuperTypes="#//AssignableArray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//AssignableArg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignableArg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" eType="#//Assignable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Arg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" upperBound="-1" eType="#//Arg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitArgList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//ArgLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgList" eSuperTypes="#//Array">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummy" eType="#//ExplicitArgList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//PrimaryExpression #//Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dictionary" eSuperTypes="#//PrimaryExpression #//Assignable #//Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictItems" eSuperTypes="#//Dictionary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummy" eType="#//ExplicitDictItems"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitDictItems">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//DictLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//DictItem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" upperBound="-1" eType="#//DictItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//DictKey"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DictKey"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lambda" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoolLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="JSLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegexLiteral" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//PrimaryExpression #//DictKey"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parenthetical" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//Body"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummy" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="For" eSuperTypes="#//Expression #//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummy" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loop" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//Expression #//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummy" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loop" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Until" eSuperTypes="#//Expression #//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dummy" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loop" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExp" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SuperCall" eSuperTypes="#//Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" eType="#//ArgList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThisAlone" eSuperTypes="#//PrimaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TryCatch" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exception" eType="#//Id"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catchBlock" eType="#//Block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finallyBlock" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//PrimaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//Case" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlock" eType="#//Block"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
