/*
* generated by Xtext
*/
package csep.example.cake.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import csep.example.cake.services.CakefileGrammarAccess;

public class CakefileParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CakefileGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected csep.example.cake.parser.antlr.internal.InternalCakefileParser createParser(XtextTokenStream stream) {
		return new csep.example.cake.parser.antlr.internal.InternalCakefileParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Cakefile";
	}
	
	public CakefileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CakefileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
