/*
* generated by Xtext
*/
package csep.example.cake.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractCakefileJavaValidator extends csep.validation.CoffeeScriptJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(csep.example.cake.cakefile.CakefilePackage.eINSTANCE);
		return result;
	}

}
