/*
* generated by Xtext
*/
package csep.example.cake;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CakefileUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return csep.example.cake.ui.internal.CakefileActivator.getInstance().getInjector("csep.example.cake.Cakefile");
	}
	
}
