/*
* generated by Xtext
*/
package csep;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CoffeeScriptUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return csep.ui.internal.CoffeeScriptActivator.getInstance().getInjector("csep.CoffeeScript");
	}
	
}
